# Setup
title: Roman Kolpak
tagline: ""
url: ""
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options


ga_analytics: G-MWLYH8TCWG

# Specify the author for blog posts
author:
  name: Roman Kolpak
  url: https://twitter.com/roman_says_hi
  email: kolpak.roman@gmail.com

# Custom vars
version: 3.0.0